# Generated by Django 5.1.2 on 2024-12-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('on_hold', 'On Hold'), ('closed', 'Closed'), ('disqualified', 'Disqualified'), ('follow_up', 'Follow-Up Required')], default='new', max_length=50),
        ),
    ]
